version: '3.1'
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=db_name
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    command: "--default-authentication-plugin=mysql_native_password"

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db_name
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    command: "postgres"
