server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:h2:mem:mydatabase
    #    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:db_name}
    #    url: jdbc:mysql://${DB_HOST:localhost}:${db.port:3306}/${DB_NAME:db_name}
    username: ${DB_USER:username}
    password: ${DB_PASSWORD:password}
    #    driver-class-name: org.postgresql.Driver
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    driverClassName: org.h2.Driver

springdoc:
  api-docs:
    enabled: ${ENABLE_SWAGGER_UI:true}
  swagger-ui:
    enabled: ${ENABLE_SWAGGER_UI:true}
