openapi: "3.0.2"
info:
  version: "0.0.1"
  title: API Specs
paths:
  /persons:
    post:
      summary: Create Person
      operationId: createPerson
      tags:
        - persons
      x-webclient-blocking: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePerson'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Person"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    get:
      summary: List Persons
      operationId: listPersons
      tags:
        - persons
      x-webclient-blocking: true
      parameters:
        - in: query
          name: pageable
          required: false
          schema:
            $ref: '#/components/schemas/Pageable'
      responses:
        '200':
          description: A paged list of persons
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Persons"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Pageable:
      type: object
      properties:
        page:
          type: integer
          format: int32
          default: 0
        size:
          type: integer
          format: int32
          default: 20
    CreatePerson:
      required:
        - name
        - age
        - phone_number
      properties:
        name:
          type: string
        age:
          type: integer
          format: int32
          minimum: 18
        phone_number:
          type: string
          format: phone
    Person:
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        age:
          type: integer
          format: int32
        phone_number:
          type: string
          format: phone
    Persons:
      type: array
      items:
        $ref: "#/components/schemas/Person"
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
